name:                ghc-gc-tune
version:             0.3.2
synopsis:            Graph performance of Haskell programs with different GC flags
description:         >-
                     ghc-gc-tune runs your compiled Haskell program with
                     different GC flags, and generates a graph of time as
                     those GC settings vary. ghc-gc-tune lets your automate
                     the task of finding good GC flags for your program, in
                     order to get the best performance from it.
                     .
                     Graphs are rendered with gnuplot, so make sure that is
                     installed.
                     .
                     Example use:
                     . 
                     > ghc -O2 --make binarytrees.hs
                     > ghc-gc-tune -t svg binarytrees 12
                     .
                     Example output:
                     .
                     <http://haskell.org/haskellwiki/Ghc-gc-tune>
                     .
                     For more information on GHC garbage collector settings,
                     see <http://www.haskell.org/ghc/docs/latest/html/users_guide/runtime-control.html#rts-options-gc>
                     .
homepage:            https://github.com/bitemyapp/ghc-gc-tune#readme
license:             BSD3
author:              Don Stewart
maintainer:          community
copyright:           https://github.com/bitemyapp/ghc-gc-tune
category:            Development
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - directory
  - process
  - filepath

executables:
  ghc-gc-tune:
    source-dirs:      src
    main:             Main.hs
    ghc-options:      -Wall -O2 -funbox-strict-fields
